# Generated by Django 2.0.5 on 2018-06-21 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='editaveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missao', models.TextField()),
                ('visao', models.TextField()),
                ('valores', models.TextField()),
                ('telefone', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='mvv',
        ),
    ]
