# Generated by Django 2.0.5 on 2018-06-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180621_2153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='editaveis',
            new_name='editavei',
        ),
    ]
