# Generated by Django 2.0.5 on 2018-06-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180621_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='editavei',
            name='email',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
