# Generated by Django 2.0.5 on 2018-06-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180628_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editavei',
            name='email',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='editavei',
            name='missao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='editavei',
            name='telefone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='editavei',
            name='valores',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='editavei',
            name='visao',
            field=models.TextField(),
        ),
    ]
